# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LivenessSDKObjCDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LivenessSDKObjCDemo
  pod 'AAINetwork', :http => 'https://prod-guardian-cv.oss-ap-southeast-5.aliyuncs.com/sdk/iOS-libraries/AAINetwork/AAINetwork-V1.0.0.tar.bz2', type: :tbz 
  pod 'AAILiveness', :http => 'https://prod-guardian-cv.oss-ap-southeast-5.aliyuncs.com/sdk/iOS-liveness-detection/2.0.3/iOS-Liveness-SDK-V2.0.3.tar.bz2', type: :tbz
end
